### PR TITLE
I:R-based de jure setup

### PR DESCRIPTION
**Pull request by IohannesIohannium**
Proposal for solving #184, moves the de jure kingdom and de jure empire setup in the I:R area (minus East Africa, India and Tibet) to resemble the I:R governorate setup.

New de jure empires map:
image

New de jure kingdoms map:
image

Somehow the game still doesn't read the new names I provided it: Kimek is actually Scythia, Daylam is actually Media, Khorasan is actually Parthia (although it could be ignored), Croatia is actually Illyria, Epirus is actually Macedonia, Wallachia is actually Dacia, Hungary is actually Pannonia, Galicia-Volhynia is actually Vistulia, Bavaria is actually Upper Germany, Burgundy is actually Transalpine Gaul, the Empire of Francia is actually the Empire of Gaul, the Byzantine Empire should appear as the Hellenic Empire. Left Poland unchanged although it represents I:R Venedia.

### CODE REVIEW

**Review by IhateTrains — CHANGES_REQUESTED** [review]
1. If the files are to be only sometimes copied to output mod, they should be outside of blankMod folder. Maybe in Data_Files/Optional_Mod_Files?
2. Don't the localization files need to be UTF8-BOM to work?

**Comment by IohannesIohannium** [comment]
1. I would rather propose this as the new default setup. We can always
remove it when the converter will craft one dynamically.
2. Oh, I screwed up the encoding again?

**Comment by IhateTrains** [comment]
> 1. I would rather propose this as the new default setup. We can always remove it when the converter will craft one dynamically.

Even it default, it should be optional and configurable through frontend.

**Comment by IohannesIohannium** [comment]
Then I'll wait until such an option is coded in somehow

**Comment by IhateTrains** [comment]
#193 expects the Imperator de jure files to be in `blankMod/optionalFiles/ImperatorDeJure`. Please put the landed titles file in `blankMod/optionalFiles/ImperatorDeJure/common/landed_titles` and localizations in `blankMod/optionalFiles/ImperatorDeJure/localization`.

**Comment by IohannesIohannium** [comment]
Done

**Review by IhateTrains — APPROVED** [review]

**Pull request merged**
