### PR TITLE
A few tests

### PR DESCRIPTION
**Pull request by IhateTrains**

### CODE REVIEW

**Review by Idhrendur — APPROVED** [review]
Looks like the linux test runner is failing, but otherwise good.

**Comment by IhateTrains** [comment]
There might be a difference in GetAllFilesInFolderRecursive's behaviour between Windows and Linux, as Windows get the correct path `TestFiles/title_history/TitlesHistory.txt`, and Linux gets `TestFiles/title_history//title_history/TitlesHistory.txt`.

**Comment by Idhrendur** [comment]
Well that's unfortunate. Just to be sure, have you added an ```ls -R``` to the workflow just to make sure the file isn't somehow ending up as ```TestFiles/title_history//title_history/TitlesHistory.txt```?

**Comment by IhateTrains** [comment]
> Well that's unfortunate. Just to be sure, have you added an `ls -R` to the workflow just to make sure the file isn't somehow ending up as `TestFiles/title_history//title_history/TitlesHistory.txt`?

I did that now and it's in correct location:
```
ImperatorToCK3Tests/build/TestFiles:
CK3ProvincesHistoryFile.txt
CoatsOfArms.txt
mod
title_history
title_map.txt

ImperatorToCK3Tests/build/TestFiles/mod:
brokenmod.mod
missingmod.mod
packedmod.mod
packedmod.zip
themod
themod.mod

ImperatorToCK3Tests/build/TestFiles/mod/themod:
README.md

ImperatorToCK3Tests/build/TestFiles/title_history:
TitlesHistory.txt
```

**Comment by Idhrendur** [comment]
How disappointing. I guess just go ahead and open an issue on the common items and merge your work here.

**Pull request merged**
