### PR TITLE
Add mappings from Inventions to Innovations (towards #163)

### PR DESCRIPTION
**Pull request by MatthewForrester**

### CODE REVIEW

**Comment by MatthewForrester** [comment]
This is a contribution towards #163

**Comment by IhateTrains** [comment]
Hi, sorry for taking so long to review it! I'm gonna finish the coding part and provide feedback after a test conversion with these mappings.

**Review by IhateTrains — CHANGES_REQUESTED** [review]
Only found one syntax error, thanks for all the mappings!

**Comment by IhateTrains** [comment]
I need to make a new release, so tweaked the file myself. Thanks again for the mappings!

**Review by IhateTrains — APPROVED** [review]

**Pull request merged**
