### PR TITLE
"Heresies in historical areas" option for religion mappings

### PR DESCRIPTION
**Pull request by IhateTrains**
The option needs text by @TinWiz

### CODE REVIEW

**Review by Idhrendur — APPROVED** [review]

**Comment by TinWiz** [comment]
> The option needs text by @TinWiz

Sorry where do I write the text?

**Comment by IhateTrains** [comment]
> > The option needs text by @TinWiz
> 
> Sorry where do I write the text?

In https://github.com/ParadoxGameConverters/ImperatorToCK3/blob/2f48a6a08c17546f71c8eef2896d6259de901f77/ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml, but just post it here and I'll commit it.

**Comment by TinWiz** [comment]
`HERESIES_IN_HISTORICAL_AREAS: "Do you want to convert with historical Gnostic heresies?"`
`HERESIES_IN_HISTORICAL_AREAS_TIP: "This option will convert some Christian and Manichaean pops in certain areas of the Imperator: Rome map to a Gnostic/Dualist faith or Christian heretical faith in the corresponding areas of the Crusader Kings III map, depending on where they appeared historically. For example, some provinces with a majority Christian or Manichaean population in I:R could be converted to Priscillianism, or Adamitism, in CK3."`

**Comment by TinWiz** [comment]
You can leave out mentioning Adamitism, as I didn't add that to the religion_map.txt that I uploaded on Discord, but they did exist in North Africa in late antiquity, though I don't think know to what degree or how cohesive it was.

**Comment by IhateTrains** [comment]
Made the regional Nestorian mapping also require this option.

**Pull request merged**
